### ISSUE TITLE
Missing mate-panel-gtk3

### ISSUE THREAD

**Issue by ed0c** [Eadrom/arch_mate#2]
# Maintainer:  eadrom eadrom@archlinux.info
# Contributor:  Martin Wimpress code@flexion.org

_ver=1.14
_pkgbase=mate-panel
pkgname=${_pkgbase}-gtk3
pkgver=${_ver}.1
pkgrel=1
pkgdesc="The MATE Panel (GTK3 version [EXPERIMENTAL])"
url="http://mate-desktop.org"
arch=('i686' 'x86_64')
license=('GPL')
depends=('dbus-glib' 'dconf' 'glib2' 'gtk3' 'gtk-update-icon-cache' 'libwnck'
         'libcanberra' 'libice' 'libmateweather-gtk3>=1.14' 'librsvg' 'libsm' 'libsoup'
         'libxau' 'mate-menus>=1.14' 'mate-desktop-gtk3>=1.14')
makedepends=('gobject-introspection' 'mate-common' 'yelp-tools')
optdepends=('yelp: for reading MATE help documents')
source=("http://pub.mate-desktop.org/releases/${_ver}/${_pkgbase}-${pkgver}.tar.xz")
groups=('mate')
conflicts=("${_pkgbase}")
sha1sums=('793a8714a47a9e00c68f9dc3b59457054e45e46a')

build() {
    cd "${srcdir}/${_pkgbase}-${pkgver}"
    ./configure \
        --prefix=/usr \
        --libexecdir=/usr/lib/${_pkgbase} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --with-gtk=3.0 \
        --enable-introspection \
        --disable-static
    make
}

package() {
    cd "${srcdir}/${_pkgbase}-${pkgver}"
    make DESTDIR="${pkgdir}" install
}

**Comment by Eadrom** [comment]
Confirmed.  Added it into the mate-panel split-package pkgbuild.
