### ISSUE TITLE
Remove patch in mate-themes

### ISSUE THREAD

**Issue by ed0c** [Eadrom/arch_mate#4]
Since the 3.20.7 version, there is no need for the fix.selection.patch
[https://github.com/mate-desktop/mate-themes/commit/49253cda2809d20b4e1968ff6be316c2c0ead54e](url)
Indeed, i can't build the package with the patch.
Please remove it from the pkgbuild

**Comment by Eadrom** [comment]
Updated mate-themes to v3.20.8 and removed patch.
