### ISSUE TITLE
Remove entries to compile mate-system-monitor-gtk2

### ISSUE THREAD

**Issue by ed0c** [Eadrom/arch_mate#5]
According to the change log
`mate-system-monitor

```
Move to GTK+3, drop GTK+2 code and --with-gtk build option`
```

there is no longer need to use --with-gtk option

**Comment by ed0c** [comment]
# Maintainer:  eadrom eadrom@archlinux.info

# Contributor:  Martin Wimpress code@flexion.org

_ver=1.14
pkgbase=mate-system-monitor
pkgname=(${pkgbase})
pkgver=${_ver}.0
pkgrel=1
pkgdesc="A system monitor for MATE"
url="http://mate-desktop.org"
arch=('i686' 'x86_64')
license=('GPL')
depends=('dconf' 'dbus-glib' 'glibmm' 'glib2' 'gtkmm' 'gtkmm3' 'libgtop' 'libwnck'
         'libwnck3' 'librsvg')
makedepends=('docbook2x' 'mate-common' 'yelp-tools')
optdepends=('yelp: for reading MATE help documents')
source=("http://pub.mate-desktop.org/releases/${_ver}/${pkgbase}-${pkgver}.tar.xz")
sha1sums=('a9045ce34fe9c116b6afae08b04030ab9c2287ae')

prepare() {
    cd "${srcdir}"
    mv "${pkgname}-${pkgver}" "${pkgbase}"
}

build() {
    cd "${srcdir}/${pkgbase}"
    ./configure \
        --prefix=/usr \
        --libexecdir=/usr/lib/${pkgbase} \
        --localstatedir=/var \
        --disable-static
    make
}

package() {
    cd "${srcdir}/${pkgbase}"
    make DESTDIR="${pkgdir}" install
}

**Comment by Eadrom** [comment]
Confirmed.  Updated PKGBUILD to remove gtk2 build instructions.
