### ISSUE TITLE
Remove mozo-gtk3

### ISSUE THREAD

**Issue by ed0c** [Eadrom/arch_mate#6]
Since mate 1.14, mozo is only avaible in GTK3.
You can remove mozo-gtk3
https://github.com/mate-desktop/mozo/commit/2c78f9151d95329e75494d6ac69eb00d59025b7c

**Comment by Eadrom** [comment]
confirmed.  Updated mozo-gtk3 to use 1.14 upstream tarball and deprecated the gtk2 pkgbuild.  Leaving in the directory mozo-gtk3 just to help remind me.  The actual pkgbuild should be set correctly.
